import React from "react";
import { BackButton } from "../../components";

export function HowItWorks() {

    return (
        <>
        <h1>How it Works</h1>
        <main>
            <div id="about">
                <p>
                    Let us guess. You're here because you have fallen out with someone else over what film you want to watch, right?
                    We've been there before. That's why we created <b>Just Pick One</b>. 
                    A platform to help you and your mates decide which film to watch in the fairest way possible.   
                </p>
                <p>
                    Simply filter through a range of film categories, 
                    swipe right for the films you want to watch, 
                    and we will show you your film match. 
                </p>
                
            </div>
            <div id="instructions">
                <p id="i1">
                    To being matching, we only require the host to have an account. 
                </p>
                <p className="i2">
                    Once logged in, you can start a new game to begin entering your groups' film preferences with our list of filters. 
                </p>
                <p className="i2">
                    If you are matching with the same group again and still have the same film preferences, you can reuse those again. 
                </p>
                <p className="i2">
                    You can also edit your groups' preferences should you wish to.
                </p>
                <p id="i3">
                    To join in on the matching, simply enter the code generated by the host and you'll enter the waiting room. 
                    If you have an account you want to use, you can also join in on the matching after logging in. 
                </p>
                <p id="4">
                    When you are ready, ready up. When everyone is ready, the host can start the matching.
                </p>
                <p id="5">
                    Your group will be presented with a random choice of films selected from your preferences. 
                    All you have to do is swipe right if you would be happy to watch the film, and left if you wouldn't. 
                </p>
                <p id="i6">
                    Once your group has swiped through all the films, you will be presented with a match.
                </p>
                    <ul>
                    <li>If you all swiped right on one film only, this film will be your match.</li> 
                    <li>If you all swiped right on multiple films, we will randomly generate a film for you as your match.</li> 
                    <li>If there was no match from your group, we will pick the highest swiped right one as your match.</li> 
                    <li>If there are multiple films with the same number of swipe rights, we will randomly generate one of those as your match.</li>
                    <li>If there are no matches, we will randomly generate a film as your match.</li>  
                    </ul>
                
                <p id="6">
                    If, for any reason, you are not happy with the film match, 
                    you can either re-generate a random match, 
                    play with a new set of films with the same preferences, 
                    or start again and choose new preferences. 
                </p>
            </div>
            <div id="outro">
                <p>
                    We hope you have fun using Just Pick One (and save your relationships in the process)!!
                </p>
            </div>
            <BackButton />
        </main>

        </>
    )
}