# Generated by Django 4.0.4 on 2022-05-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_alter_preferences_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='user',
        ),
    ]
